/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ChartHint = ("line" | "bar" | "area" | "point" | "heatmap" | "big_number") | null;
export type ChartType = string | null;
export type CompiledSql = string | null;
export type DataMaxTs = string | null;
export type Error = string | null;
export type ErrorReason = string | null;
export type FetchedAt = string | null;
export type FromCache = boolean;
export type HintRejected = boolean;
export type Restatement = string;
export type RowCount = number;
export type Rows = {
  [k: string]: unknown;
}[];
/**
 * @maxItems 2
 */
export type Dimensions = [] | [DimensionRef] | [DimensionRef, DimensionRef];
export type Field = string;
export type Grain = ("day" | "month" | "quarter" | "year") | null;
export type Entity = string;
export type Field1 = string;
export type Op = "=" | "!=" | "in" | "between" | "in_year" | "last_n_days";
export type Value = string | number | boolean | (string | number | boolean)[] | null;
export type Filters = Filter[];
export type Limit = number;
/**
 * @minItems 1
 */
export type Measures = [string, ...string[]];
export type Dir = "asc" | "desc";
export type Field2 = string;
export type OrderBy = OrderBy1[];
export type State = "empty" | "ready" | "broken";
export type VegaSpec = {
  [k: string]: unknown;
} | null;

/**
 * A single root so json2ts emits one file with shared $defs.
 */
export interface ApiContract {
  render: Render;
  semantic_query: SemanticQuery;
  [k: string]: unknown;
}
/**
 * Everything a card needs to draw itself, including the honest version
 * of where the numbers came from and how old they are.
 */
export interface Render {
  chart_hint?: ChartHint;
  chart_type?: ChartType;
  compiled_sql?: CompiledSql;
  data_max_ts?: DataMaxTs;
  error?: Error;
  error_reason?: ErrorReason;
  fetched_at?: FetchedAt;
  from_cache?: FromCache;
  hint_rejected?: HintRejected;
  restatement?: Restatement;
  row_count?: RowCount;
  rows?: Rows;
  semantic_query?: SemanticQuery | null;
  state: State;
  vega_spec?: VegaSpec;
  [k: string]: unknown;
}
/**
 * One entity, N measures, up to 2 dimensions. Deliberately no joins
 * beyond declared `via` paths, no window functions, no subqueries, and
 * no DML — those are not hard here, they are impossible.
 */
export interface SemanticQuery {
  dimensions?: Dimensions;
  entity: Entity;
  filters?: Filters;
  limit?: Limit;
  measures: Measures;
  order_by?: OrderBy;
}
export interface DimensionRef {
  field: Field;
  grain?: Grain;
}
export interface Filter {
  field: Field1;
  op: Op;
  value?: Value;
}
export interface OrderBy1 {
  dir?: Dir;
  field: Field2;
}
