/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ChartHint =
  | (
      | "line"
      | "bar"
      | "area"
      | "point"
      | "heatmap"
      | "big_number"
      | "pie"
      | "donut"
      | "stacked_bar"
      | "normalised_bar"
      | "scatter"
      | "bubble"
      | "map"
    )
  | null;
export type ChartRows =
  | {
      [k: string]: unknown;
    }[]
  | null;
export type ChartType = string | null;
export type CompiledSql = string | null;
export type DataMaxTs = string | null;
export type Error = string | null;
export type ErrorReason = string | null;
export type FetchedAt = string | null;
export type FromCache = boolean;
export type HintRejected = boolean;
export type Restatement = string;
export type RowCount = number;
export type Rows = {
  [k: string]: unknown;
}[];
/**
 * @maxItems 3
 */
export type Dimensions =
  [] | [DimensionRef] | [DimensionRef, DimensionRef] | [DimensionRef, DimensionRef, DimensionRef];
export type Field = string;
export type Grain = ("day" | "month" | "quarter" | "year") | null;
export type Entity = string;
export type Field1 = string;
export type Op = "=" | "!=" | "in" | "between" | "in_year" | "last_n_days";
export type Value = string | number | boolean | (string | number | boolean)[] | null;
export type Filters = Filter[];
export type Limit = number;
/**
 * @minItems 1
 */
export type Measures = [MeasureRef, ...MeasureRef[]];
export type Name = string;
export type Per = string | null;
export type Transform =
  | (
      | "percent_of_total"
      | "previous_period"
      | "period_change"
      | "period_change_pct"
      | "cumulative"
      | "moving_average"
      | "rank"
      | "ratio"
    )
  | null;
export type Window = number | null;
export type Dir = "asc" | "desc";
export type Field2 = string;
export type OrderBy = OrderBy1[];
export type State = "empty" | "ready" | "broken";
export type VegaSpec = {
  [k: string]: unknown;
} | null;

/**
 * A single root so json2ts emits one file with shared $defs.
 */
export interface ApiContract {
  render: Render;
  semantic_query: SemanticQuery;
  [k: string]: unknown;
}
/**
 * Everything a card needs to draw itself, including the honest version
 * of where the numbers came from and how old they are.
 */
export interface Render {
  chart_hint?: ChartHint;
  chart_rows?: ChartRows;
  chart_type?: ChartType;
  compiled_sql?: CompiledSql;
  data_max_ts?: DataMaxTs;
  error?: Error;
  error_reason?: ErrorReason;
  fetched_at?: FetchedAt;
  from_cache?: FromCache;
  hint_rejected?: HintRejected;
  restatement?: Restatement;
  row_count?: RowCount;
  rows?: Rows;
  semantic_query?: SemanticQuery | null;
  state: State;
  vega_spec?: VegaSpec;
  [k: string]: unknown;
}
/**
 * One entity, N measures, up to 3 dimensions.
 *
 * Deliberately still no joins beyond declared `via` paths, no subqueries,
 * no free-form expressions and no DML — those are not hard here, they are
 * impossible. Window functions arrived as a closed `Transform` enum the
 * compiler implements, which is a different thing from letting the model
 * write one.
 */
export interface SemanticQuery {
  dimensions?: Dimensions;
  entity: Entity;
  filters?: Filters;
  limit?: Limit;
  measures: Measures;
  order_by?: OrderBy;
}
export interface DimensionRef {
  field: Field;
  grain?: Grain;
}
export interface Filter {
  field: Field1;
  op: Op;
  value?: Value;
}
/**
 * A measure, optionally transformed.
 *
 * Bare strings are still legal everywhere a measure is named -- every
 * saved card and every existing fixture predates this model -- and are
 * normalised into `MeasureRef(name=...)` on the way in.
 */
export interface MeasureRef {
  name: Name;
  per?: Per;
  transform?: Transform;
  window?: Window;
}
export interface OrderBy1 {
  dir?: Dir;
  field: Field2;
}
